### PR TITLE
Rocky Linux 8

### PR DESCRIPTION
**Pull request by panda1100**
Rocky Linux 8 based Intel oneAPI containers
Singularity is now Linux Foundation Project and renamed to Apptainer

### CODE REVIEW

**Comment by luisfponce** [comment]
@gorozco1 thoughts?

**Comment by panda1100** [comment]
> @gorozco1 thoughts?
> 
> 

If I can do something for you to merge this request, please let me know. I'm happy to support.

I used oneAPI to build [OpenRadioss](https://github.com/OpenRadioss/OpenRadioss) and the [Apptainer (former Singularity) definition file](https://github.com/OpenRadioss/OpenRadioss/blob/main/Apptainer/openradioss_intel.def) is merged into OpenRadioss repository.

It would be great if this PR merged and so that we can simplify that definition file.

**Comment by jonathanspw** [comment]
Singularity is now singularity-ce, not apptainer

**Comment by panda1100** [comment]
@jonathanspw Singularity renamed to Apptainer. Please see https://www.linuxfoundation.org/press/press-release/new-linux-foundation-project-accelerates-collaboration-on-container-systems-between-enterprise-and-high-performance-computing-environments

**Comment by jonathanspw** [comment]
> @jonathanspw Singularity renamed to Apptainer. Please see https://www.linuxfoundation.org/press/press-release/new-linux-foundation-project-accelerates-collaboration-on-container-systems-between-enterprise-and-high-performance-computing-environments

No, the project split in half.  Singularity-ce is closer to the original than apptainer.

**Comment by tingleby** [comment]
Apologies for the radio silence. We have Rocky Linux 9 images built, would that suffice? 

I am going to close the PR but thanks a bunch for the contribution anyway!

**Comment by panda1100** [comment]
Hello @tingleby -san,

First of all I would like to say BIG thanks for the release of the Rocky9 based image.

Many of HPC users in industries they use Rocky8 for their compute resources. That's simply because some of their important applications primarily supports Rocky8.

In that respect, if users have options to use EL8 (Rocky8) and EL9 (Rocky9), that must be great.

Please let me know if you need anything from me and thank you again for your efforts.

**Pull request closed without merging**
